apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  # workflow:
  #   maxConcurrentWorkflowInvocations: 10
  #   maxConcurrentActivityInvocations: 2000
  # tracing:
  #   samplingRate: "1"
  #   zipkin:
  #     endpointAddress: "http://host.docker.internal:9411/api/v2/spans"
